CREATE OR replace FUNCTION  DESCRICAO_MES(CODIGOMES integer)
RETURNS TABLE(
    MES VARCHAR(20),
    ABREV VARCHAR(20))
AS $$
begin
    MES   := TO_CHAR(CAST('1900-'||LPAD(CAST(CODIGOMES AS TEXT),2,'0')||'-01' AS DATE), 'TMMonth');
    ABREV := LEFT(MES, 3); 
    RETURN NEXT;
END; 
$$ LANGUAGE PLPGSQL;
